# Generated by Django 5.0.4 on 2024-05-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='kelometrage',
            new_name='prix_jours',
        ),
        migrations.RemoveField(
            model_name='car',
            name='prix',
        ),
        migrations.AddField(
            model_name='car',
            name='kilometrage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='disponibilite',
            field=models.CharField(choices=[('louer', 'Louer'), ('parc', 'Parc')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='marque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='matricule',
            field=models.CharField(max_length=100),
        ),
    ]
