# Generated by Django 5.0.4 on 2024-05-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0002_rename_kelometrage_car_prix_jours_remove_car_prix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='prix_jours',
            new_name='prixjours',
        ),
    ]
