# Generated by Django 5.0.4 on 2024-05-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0003_rename_prix_jours_car_prixjours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='prixjours',
            new_name='prix_jours',
        ),
    ]
